import { PUBLICATION_STATUS } from "./config";

const PUBLICATION_STATUS_OPTIONS = [
    { value: PUBLICATION_STATUS.DRAFT, label: PUBLICATION_STATUS.DRAFT },
    { value: PUBLICATION_STATUS.PUBLISHED, label: PUBLICATION_STATUS.PUBLISHED },
];

export { PUBLICATION_STATUS_OPTIONS };